server:
  port: 8082
  tomcat:
      uri-encoding: UTF-8


#spring
spring:
  #数据库的配置
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    hikari:
      minimum-idle: 10
      maximum-pool-size: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      pool-name: wolfking-jeesite-pool


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.model

#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql

